# Generated by Django 6.0.4 on 2026-04-22 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('facid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('membercost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guestcost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('initialoutlay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthlymaintenance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('memid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('zipcode', models.IntegerField()),
                ('telephone', models.CharField(max_length=20)),
                ('joindate', models.DateTimeField()),
                ('recommendedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.member')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField()),
                ('slots', models.IntegerField()),
                ('facid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.facility')),
                ('memid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.member')),
            ],
        ),
    ]
